### ISSUE TITLE
Deprecated functions error messages

### ISSUE THREAD

**Issue by rezeau** [moodleou/moodle-report_embedquestion#10]
Moodle 3.11.1 (Build: 20210712) on localhost Windows
Debug messages DEVELOPER: extra Moodle debug messages for developers 
Embedded questions progress version 2021010700

When viewing Embedded questions progress I get these error messages:

get_all_user_name_fields() is deprecated. Please use the \core_user\fields API instead
    line 3391 of \lib\deprecatedlib.php: call to debugging()
    line 128 of \report\embedquestion\classes\utils.php: call to get_all_user_name_fields()
    line 96 of \report\embedquestion\classes\latest_attempt_table.php: call to report_embedquestion\utils::get_user_fields()
    line 90 of \report\embedquestion\classes\output\multi_user_course_report.php: call to report_embedquestion\latest_attempt_table->__construct()
    line 74 of \report\embedquestion\index.php: call to report_embedquestion\output\multi_user_course_report->display_download_content()

get_extra_user_fields() is deprecated. Please use the \core_user\fields API instead.
    line 3331 of \lib\deprecatedlib.php: call to debugging()
    line 128 of \report\embedquestion\classes\utils.php: call to get_extra_user_fields()
    line 96 of \report\embedquestion\classes\latest_attempt_table.php: call to report_embedquestion\utils::get_user_fields()
    line 90 of \report\embedquestion\classes\output\multi_user_course_report.php: call to report_embedquestion\latest_attempt_table->__construct()
    line 74 of \report\embedquestion\index.php: call to report_embedquestion\output\multi_user_course_report->display_download_content()

**Comment by timhunt** [comment]
We have a fix for this which will hopefully be pushed here soon.

**Comment by timhunt** [comment]
I am working on pushing the new code now, so closing this.
