### ISSUE TITLE
Error during Moodle 3.7 backup & restore

### ISSUE THREAD

**Issue by davosmith** [moodleou/moodle-report_embedquestion#2]
https://github.com/moodleou/moodle-report_embedquestion/commit/760677ecbd6d90e59afcd397ed946faccd5c986f#commitcomment-36283008

@timhunt this is giving a fatal error during backup + restore on a Moodle 3.7 site - the backup code finds the bacup_report_embedquestion_plugin.php and restore_report_embedquestion_plugin.php files and expects them to contain the appropriate class definition. When they don't an error occurs.

**Comment by timhunt** [comment]
Sorry I have not had time to fix this yet.

In the short term, a work-around is to delete the backup folder from inside this plugin.

**Comment by davosmith** [comment]
Thanks for the response, Tim - for the particular customer affected by this, I've deleted the backup folder already, but thought you'd want to know in order to implement a more general solution.

**Comment by timhunt** [comment]
Absolutely. Thanks for the report.

**Comment by timhunt** [comment]
The other option is to back-port the https://tracker.moodle.org/browse/MDL-66709 change. Sorry, I have not had time to deal with this fully.

**Comment by neeesn** [comment]
Its the same in Moodle 3.8.4 - Cant use the Sharing Cart, since it uses the backup/restore.

**Comment by timhunt** [comment]
As above: delete the report/embedquestion/backup folder.

**Comment by timhunt** [comment]
I that by skillfully waiting long enough, this issue now does not affect any supported Moodle version. Anyway, from now on I am only supporting Moodle 3.9+, so closing this. 

The work-around of deleting the backup folder is still valid for anyone wanting to use an other Moodle version.
