### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dinism** [moodleou/moodle-report_embedquestion#4]
When tried to see last attempt
![imagem](https://user-images.githubusercontent.com/14828021/86010144-e6a56c80-ba12-11ea-93c5-a8c1fd2fe416.png)
I got this:
![imagem](https://user-images.githubusercontent.com/14828021/86010255-0dfc3980-ba13-11ea-90df-17c99d693faf.png)

**Comment by timhunt** [comment]
Very strange. When I try on our sever, that link works.

Are you able to debug this at all?

**Comment by dinism** [comment]
What should i do? I Have developer option on debugging.
This question is on a Label at the course (section 1).
It's a multichoice question type. Added via atto button.
![imagem](https://user-images.githubusercontent.com/14828021/86040485-0604bf80-ba3c-11ea-998e-1de9d9b14cc7.png)
![imagem](https://user-images.githubusercontent.com/14828021/86040517-1452db80-ba3c-11ea-9930-17638a4a9b32.png)
![imagem](https://user-images.githubusercontent.com/14828021/86040533-1c128000-ba3c-11ea-8093-67c139995bb8.png)

**Comment by timhunt** [comment]
I think the most likely cause of this error is some messed up data in your database. It seems there is an attempt where in cannot work out which question has been attempted - and that is what leads to this error. However, I cannot think how it got into that state.

**Comment by timhunt** [comment]
No further information on how to reproduce this issue, so I will have to close this.

If it happens again, please create a new issue with more details.
