### ISSUE TITLE
Class 'backup_execution_step' not found

### ISSUE THREAD

**Issue by nadavkav** [moodleou/moodle-report_embedquestion#7]
While trying to restore a deleted H5P activity from the course recycle bin, we get the following error message:

×Debug info:
Error code: generalexceptionmessage
×Stack trace:
line 33 of /backup/moodle2/backup_stepslib.php: Error thrown
line 26 of /report/embedquestion/backup/moodle2/backup_report_embedquestion_plugin.class.php: call to require_once()
line 283 of /backup/util/plan/restore_structure_step.class.php: call to require_once()
line 4238 of /backup/moodle2/restore_stepslib.php: call to restore_structure_step->add_plugin_structure()
line 84 of /backup/util/plan/restore_structure_step.class.php: call to restore_module_structure_step->define_structure()
line 181 of /backup/util/plan/base_task.class.php: call to restore_structure_step->execute()
line 210 of /backup/moodle2/restore_activity_task.class.php: call to base_task->execute()
line 178 of /backup/util/plan/base_plan.class.php: call to restore_activity_task->execute()
line 168 of /backup/util/plan/restore_plan.class.php: call to base_plan->execute()
line 384 of /backup/controller/restore_controller.class.php: call to restore_plan->execute()
line 265 of /admin/tool/recyclebin/classes/course_bin.php: call to restore_controller->execute_plan()
line 101 of /admin/tool/recyclebin/index.php: call to tool_recyclebin\course_bin->restore_item()

Temporarily deleting the report/embedquestion and restarting the restore process worked around this issue, and I was able to restore the H5P activity successfully.

**Comment by timhunt** [comment]
This has already been fixed, and I am about to push a new version. Closing.
