### ISSUE TITLE
Receiving this error when trying to backup a course

### ISSUE THREAD

**Issue by elektrosmart** [moodleou/moodle-report_embedquestion#8]
![image](https://user-images.githubusercontent.com/25979837/120884284-a76d9b80-c625-11eb-9f60-4f4210fdc2e5.png)

This is the debug info
![image](https://user-images.githubusercontent.com/25979837/120884590-4941b800-c627-11eb-8f56-9b8a24660c2e.png)

**Comment by timhunt** [comment]
No idea why this is not working. Which Moodle version are you using?

**Comment by elektrosmart** [comment]
Hi Tim, thanks for having a look.
V 3.6.10

**Comment by elektrosmart** [comment]
By the way - absolutely great plugin.

**Comment by timhunt** [comment]
Ah! well that explains why you are seeing this!

Backup and restore for this plugin was only supported in Moodle 3.8+ (it reqired a core change MDL-66709), and recent versions of this plugin only support Moodle 3.9 anyway.

The best work-around for you is to go into the plugin folder in your Moodle (report/embedquestion) and delete the /backup folder in there. Then, the rest of the plugin will work, and it won't break backup and restore of other things.

I am going to close this issue now.

**Comment by elektrosmart** [comment]
Great work - thanks
